name: build-and-deploy
on:
    push:
        branches:
            - main
    repository_dispatch:
        types: [datocms_deploy_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: mkdir src/data
            - run: npm i -g surge
            - run: npm i
            - name: "Build"
              run: npx gatsby build
              env:
                  DATO_CMS_API_TOKEN: ${{ secrets.DATO_CMS_API_TOKEN }}
            - name: "Deploy"
              run: surge public ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_DEPLOY_TOKEN }}
    notify_success:
        runs-on: ubuntu-latest
        needs: [build]
        if: ${{ github.event.client_payload.event_type == 'datocms_deploy_request' && needs.build.result == 'success' }}
        steps:
            - run: curl -n -X POST https://webhooks.datocms.com/${{ secrets.DATO_CMS_NOTIFY_HASH }}/deploy-results -H 'Content-Type:application/json' -d '{ "status":"success" }'
    notify_failure:
        runs-on: ubuntu-latest
        needs: [build]
        if: ${{ github.event.client_payload.event_type == 'datocms_deploy_request' && needs.build.result == 'failure' }}
        steps:
            - run: curl -n -X POST https://webhooks.datocms.com/${{ secrets.DATO_CMS_NOTIFY_HASH }}/deploy-results -H 'Content-Type:application/json' -d '{ "status":"error" }'
